name: 删除所有Actions记录

on: workflow_dispatch

jobs:
  release_freebsd:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.21' ]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
            token: ${{ secrets.MY_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 0
